variables:
  GIT_DEPTH: "1"

stages:
  - develop-build_deb
  - release-ready_to_upload

develop-build_deb:
  tags:
    - Runner-Stretch
  stage: develop-build_deb
  before_script:
    - echo "deb http://ibg-linux-apt.moxa.com:8080/mirror-stretch/Debian9.13_20200718/ stretch main" >> /etc/apt/sources.list.d/moxa.source.list
    - curl -fsSL http://ibg-linux-apt.moxa.com:8080/ibg-linux-apt.gpg | apt-key add -
    - dpkg --add-architecture armhf
    - apt-get update
    - apt-get install -y --allow-unauthenticated
      debhelper devscripts quilt bc
      libncurses5-dev liblz4-tool u-boot-tools device-tree-compiler
      build-essential crossbuild-essential-armhf
      jq unzip
    - apt-get build-dep -y ./
  script:
    - dpkg-buildpackage -us -uc -aarmhf
    - dpkg-buildpackage -us -uc
  after_script:
    - mv ../*.buildinfo .
    - mv ../*.changes .
    - mv ../*.deb .
    - mv ../*.dsc .
    - mv ../*.tar.* .
  artifacts:
    name: "${CI_PROJECT_NAME}"
    paths:
      - "*.buildinfo"
      - "*.changes"
      - "*.deb"
      - "*.dsc"
      - "*.tar.*"

release-ready_to_upload:
  tags:
    - Runner-Stretch
  stage: release-ready_to_upload
  only:
    refs:
    - 4.4.176-cip31-rt23/stretch/master
  dependencies:
    - develop-build_deb
  when: manual
  script:
    - mkdir -p /cache/stretch/mil1-internal-release/
    - cp *.deb *.dsc *.tar.* /cache/stretch/mil1-internal-release/
    - ls /cache/stretch/mil1-internal-release/
